import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Check, Clipboard, Loader2, Mail, Search, Users } from "lucide-react";
import { toast } from "sonner";
import { WhatsAppIcon } from "@/components/icons/WhatsAppIcon";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { getLandingLead, listLandingLeads, updateLandingLead, type LandingLead, type LandingLeadMetrics, type LandingLeadStatus } from "@/service/landingLeadService";
import { maskCnpj, maskPhone } from "@/utils/leadForm";

const statuses: Array<{ value: LandingLeadStatus; label: string }> = [{ value: "new", label: "Novo" }, { value: "in_contact", label: "Em contato" }, { value: "converted", label: "Convertido" }, { value: "discarded", label: "Descartado" }];
const labelStatus = (status: LandingLeadStatus) => statuses.find((item) => item.value === status)?.label || status;
const dateTime = (value?: string | null) => value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : "-";

export function SuperAdminLandingLeadsPage() {
  const [items, setItems] = useState<LandingLead[]>([]); const [metrics, setMetrics] = useState<LandingLeadMetrics>({ total: 0, new: 0, inContact: 0, converted: 0 });
  const [filters, setFilters] = useState({ q: "", status: "" }); const [applied, setApplied] = useState(filters); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<LandingLead | null>(null); const [detailsLoading, setDetailsLoading] = useState(false); const [saving, setSaving] = useState(false); const [edit, setEdit] = useState({ status: "new" as LandingLeadStatus, notes: "", contactedAt: "" });
  const load = useCallback(async () => { setLoading(true); try { const result = await listLandingLeads({ q: applied.q || undefined, status: (applied.status || undefined) as LandingLeadStatus | undefined, page, limit: 15, sortOrder: "desc" }); setItems(result.items); setMetrics(result.metrics); setTotalPages(result.totalPages); } catch { toast.error("Não foi possível carregar os contatos."); } finally { setLoading(false); } }, [applied, page]);
  useEffect(() => { void load(); }, [load]);
  function search(event: FormEvent) { event.preventDefault(); setPage(1); setApplied(filters); }
  async function openLead(id: string) { setDetailsLoading(true); try { const lead = await getLandingLead(id); setSelected(lead); setEdit({ status: lead.status, notes: lead.notes || "", contactedAt: lead.contactedAt ? new Date(lead.contactedAt).toISOString().slice(0, 16) : "" }); } catch { toast.error("Não foi possível abrir o contato."); } finally { setDetailsLoading(false); } }
  async function save() { if (!selected || saving) return; setSaving(true); try { const updated = await updateLandingLead(selected.id, { status: edit.status, notes: edit.notes || null, contactedAt: edit.contactedAt ? new Date(edit.contactedAt).toISOString() : null }); setSelected(updated); toast.success("Atendimento atualizado."); await load(); } catch { toast.error("Não foi possível salvar as alterações."); } finally { setSaving(false); } }
  async function copy(value: string, label: string) { await navigator.clipboard.writeText(value); toast.success(`${label} copiado.`); }
  return <div className="space-y-6">
    <section className="rounded-xl border border-primary/20 bg-primary/10 p-6"><div className="flex gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary"><Users size={20} /></div><div><h2 className="text-xl font-semibold">Contatos interessados</h2><p className="text-sm text-muted-foreground">Leads captados pelo formulário de WhatsApp da Landing Page.</p></div></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Total",metrics.total],["Novos",metrics.new],["Em contato",metrics.inContact],["Convertidos",metrics.converted]].map(([label,value]) => <div key={label} className="rounded-xl border border-border bg-card p-5"><p className="text-sm text-muted-foreground">{label}</p><strong className="mt-1 block text-2xl text-foreground">{value}</strong></div>)}</section>
    <section className="overflow-hidden rounded-xl border border-border bg-card">
      <form onSubmit={search} className="flex flex-col gap-3 border-b border-border p-4 sm:flex-row"><Input value={filters.q} onChange={(e) => setFilters((f) => ({ ...f, q: e.target.value }))} placeholder="Buscar nome, e-mail, telefone ou CNPJ" className="sm:max-w-md" /><select value={filters.status} onChange={(e) => setFilters((f) => ({ ...f, status: e.target.value }))} className="h-9 rounded-md border border-input bg-background px-3 text-sm"><option value="">Todos os status</option>{statuses.map((s) => <option key={s.value} value={s.value}>{s.label}</option>)}</select><Button type="submit" className="gap-2"><Search size={15} />Buscar</Button></form>
      <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b border-border text-left text-xs uppercase text-muted-foreground">{["Nome","E-mail","Telefone","CNPJ","Origem","Status","Cadastro"].map((h) => <th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={7} className="p-10 text-center text-muted-foreground"><Loader2 className="mx-auto mb-2 animate-spin" />Carregando...</td></tr> : items.length === 0 ? <tr><td colSpan={7} className="p-10 text-center text-muted-foreground">Nenhum contato encontrado.</td></tr> : items.map((lead) => <tr key={lead.id} tabIndex={0} onClick={() => void openLead(lead.id)} onKeyDown={(e) => { if (e.key === "Enter") void openLead(lead.id); }} className="cursor-pointer border-b border-border hover:bg-secondary/40"><td className="px-4 py-4 font-medium">{lead.name}</td><td className="px-4 py-4">{lead.email}</td><td className="px-4 py-4">{maskPhone(lead.phone)}</td><td className="px-4 py-4">{lead.cnpj ? maskCnpj(lead.cnpj) : "-"}</td><td className="px-4 py-4">Landing WhatsApp</td><td className="px-4 py-4"><span className="rounded-full bg-primary/10 px-2 py-1 text-xs text-primary">{labelStatus(lead.status)}</span></td><td className="px-4 py-4">{dateTime(lead.createdAt)}</td></tr>)}</tbody></table></div>
      <div className="flex items-center justify-between border-t border-border p-4 text-sm"><span className="text-muted-foreground">Página {page} de {totalPages}</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled={page === 1 || loading} onClick={() => setPage((p) => p - 1)}>Anterior</Button><Button variant="outline" size="sm" disabled={page >= totalPages || loading} onClick={() => setPage((p) => p + 1)}>Próxima</Button></div></div>
    </section>
    {detailsLoading && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div>}
    <Dialog open={Boolean(selected)} onOpenChange={(open) => { if (!open && !saving) setSelected(null); }}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{selected?.name}</DialogTitle><DialogDescription>Dados completos e acompanhamento comercial.</DialogDescription></DialogHeader>{selected && <div className="space-y-5">
      <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-lg border p-3"><span className="text-xs text-muted-foreground">Telefone</span><p className="font-medium">{maskPhone(selected.phone)}</p><div className="mt-2 flex gap-2"><Button size="sm" variant="outline" asChild><a href={`https://wa.me/55${selected.phone}`} target="_blank" rel="noreferrer"><WhatsAppIcon size={14} className="text-emerald-600" /> WhatsApp</a></Button><Button size="icon" variant="outline" onClick={() => void copy(selected.phone,"Telefone")}><Clipboard size={14} /></Button></div></div><div className="rounded-lg border p-3"><span className="text-xs text-muted-foreground">E-mail</span><p className="break-all font-medium">{selected.email}</p><div className="mt-2 flex gap-2"><Button size="sm" variant="outline" asChild><a href={`mailto:${selected.email}`}><Mail size={14} /> E-mail</a></Button><Button size="icon" variant="outline" onClick={() => void copy(selected.email,"E-mail")}><Clipboard size={14} /></Button></div></div></div>
      <div className="grid gap-3 sm:grid-cols-3"><div><Label>Origem</Label><p className="mt-1 text-sm">Landing WhatsApp</p></div><div><Label>CNPJ</Label><p className="mt-1 text-sm">{selected.cnpj ? maskCnpj(selected.cnpj) : "Não informado"}</p></div><div><Label>Cadastro</Label><p className="mt-1 text-sm">{dateTime(selected.createdAt)}</p></div></div>
      <div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="lead-status">Status</Label><select id="lead-status" value={edit.status} onChange={(e) => setEdit((v) => ({ ...v, status: e.target.value as LandingLeadStatus }))} className="mt-2 h-10 w-full rounded-md border bg-background px-3 text-sm">{statuses.map((s) => <option key={s.value} value={s.value}>{s.label}</option>)}</select></div><div><Label htmlFor="lead-contacted">Contato realizado em</Label><Input id="lead-contacted" type="datetime-local" value={edit.contactedAt} onChange={(e) => setEdit((v) => ({ ...v, contactedAt: e.target.value }))} className="mt-2" /></div></div>
      <div><Label htmlFor="lead-notes">Observações internas</Label><Textarea id="lead-notes" rows={5} value={edit.notes} onChange={(e) => setEdit((v) => ({ ...v, notes: e.target.value }))} placeholder="Registre o histórico do atendimento." className="mt-2" /></div>
      <Button onClick={() => void save()} disabled={saving} className="w-full gap-2">{saving ? <Loader2 className="animate-spin" size={16} /> : <Check size={16} />}Salvar atendimento</Button>
    </div>}</DialogContent></Dialog>
  </div>;
}
