import { type FormEvent, useCallback, useEffect, useState } from "react";
import { Banknote, CalendarDays, CircleDollarSign, Loader2, Plus, RotateCcw, WalletCards, type LucideIcon } from "lucide-react";
import { toast } from "sonner";

import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { createFinancialPayment, listDailyFinancialPayments, type DailyFinancialResponse, type FinancialPaymentMethod, type FinancialPaymentStatus } from "@/service/financialService";
import { listSuperAdminSalons, type SuperAdminSalon } from "@/service/superAdminService";

const today = new Date().toLocaleDateString("en-CA", { timeZone: "America/Sao_Paulo" });
const methodLabels: Record<FinancialPaymentMethod, string> = { pix: "PIX", credit_card: "Cartão", boleto: "Boleto", cash: "Dinheiro", bank_transfer: "Transferência", other: "Outro" };
const statusLabels: Record<FinancialPaymentStatus, string> = { paid: "Recebido", pending: "Pendente", refunded: "Estornado", cancelled: "Cancelado" };
const emptyResponse: DailyFinancialResponse = { items: [], total: 0, page: 1, limit: 20, totalPages: 1, summary: { received: 0, pending: 0, refunded: 0, paymentsCount: 0 } };

function currency(value: number) { return Number(value || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }); }
function dateTime(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "-" : date.toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" }); }

export function SuperAdminFinancialPage() {
  const [date, setDate] = useState(today); const [search, setSearch] = useState(""); const [method, setMethod] = useState<FinancialPaymentMethod | "">(""); const [status, setStatus] = useState<FinancialPaymentStatus | "">(""); const [page, setPage] = useState(1);
  const [data, setData] = useState<DailyFinancialResponse>(emptyResponse); const [loading, setLoading] = useState(true); const [modalOpen, setModalOpen] = useState(false); const [salons, setSalons] = useState<SuperAdminSalon[]>([]); const [salonsLoading, setSalonsLoading] = useState(false); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ salonId: "", amount: "", paidAt: today, paymentMethod: "pix" as FinancialPaymentMethod, reference: "", notes: "" });

  const load = useCallback(async () => { setLoading(true); try { setData(await listDailyFinancialPayments({ date, search: search.trim() || undefined, paymentMethod: method || undefined, status: status || undefined, page, limit: 20 })); } catch (error) { setData(emptyResponse); toast.error((error as { response?: { data?: { message?: string } } })?.response?.data?.message || "Não foi possível carregar os lançamentos financeiros."); } finally { setLoading(false); } }, [date, method, page, search, status]);
  useEffect(() => { void load(); }, [load]);

  async function openNewPayment() { setModalOpen(true); if (salons.length) return; setSalonsLoading(true); try { setSalons((await listSuperAdminSalons({ page: 1, limit: 100, sortBy: "name", sortOrder: "asc" })).items); } catch { toast.error("Não foi possível carregar os salões."); } finally { setSalonsLoading(false); } }
  async function submitPayment(event: FormEvent) { event.preventDefault(); const amount = Number(form.amount.replace(",", ".")); if (!form.salonId || !Number.isFinite(amount) || amount <= 0 || !form.paidAt) { toast.error("Informe salão, valor e data do recebimento."); return; } setSaving(true); try { await createFinancialPayment({ salonId: form.salonId, amount, paidAt: `${form.paidAt}T12:00:00`, paymentMethod: form.paymentMethod, reference: form.reference.trim() || undefined, notes: form.notes.trim() || undefined }); toast.success("Pagamento registrado com sucesso."); setModalOpen(false); setForm({ salonId: "", amount: "", paidAt: date, paymentMethod: "pix", reference: "", notes: "" }); await load(); } catch (error) { toast.error((error as { response?: { data?: { message?: string } } })?.response?.data?.message || "Não foi possível registrar o pagamento."); } finally { setSaving(false); } }
  function submitFilters(event: FormEvent) { event.preventDefault(); setPage(1); }

  return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold text-foreground">Financeiro diário</h2><p className="mt-1 text-sm text-muted-foreground">Acompanhe os recebimentos dos salões e registre pagamentos manuais.</p></div><button type="button" onClick={() => void openNewPayment()} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90"><Plus size={16} />Registrar pagamento</button></div>
    <form onSubmit={submitFilters} className="flex flex-wrap gap-2 rounded-xl border border-border bg-card p-3"><input type="date" value={date} onChange={(event) => { setDate(event.target.value); setPage(1); }} className="h-9 rounded-lg border border-border bg-background px-3 text-sm" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar salão ou referência" className="h-9 min-w-52 flex-1 rounded-lg border border-border bg-background px-3 text-sm" /><select value={method} onChange={(event) => { setMethod(event.target.value as FinancialPaymentMethod | ""); setPage(1); }} className="h-9 rounded-lg border border-border bg-background px-3 text-sm"><option value="">Todos os meios</option>{Object.entries(methodLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={status} onChange={(event) => { setStatus(event.target.value as FinancialPaymentStatus | ""); setPage(1); }} className="h-9 rounded-lg border border-border bg-background px-3 text-sm"><option value="">Todos os status</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button type="submit" className="h-9 rounded-lg border border-border px-4 text-sm font-medium hover:bg-secondary">Filtrar</button></form>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><SummaryCard icon={CircleDollarSign} label="Recebido no dia" value={currency(data.summary.received)} tone="text-emerald-600" /><SummaryCard icon={WalletCards} label="Pagamentos recebidos" value={String(data.summary.paymentsCount)} /><SummaryCard icon={CalendarDays} label="Pendente" value={currency(data.summary.pending)} tone="text-amber-600" /><SummaryCard icon={RotateCcw} label="Estornado" value={currency(data.summary.refunded)} tone="text-destructive" /></div>
    <div className="overflow-hidden rounded-xl border border-border bg-card"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-border text-left text-xs uppercase tracking-wider text-muted-foreground"><th className="px-5 py-3">Horário</th><th className="px-5 py-3">Salão</th><th className="px-5 py-3">Plano</th><th className="px-5 py-3">Meio</th><th className="px-5 py-3">Referência</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Valor</th></tr></thead><tbody>{loading ? <tr><td colSpan={7} className="py-12 text-center text-muted-foreground"><Loader2 className="mx-auto animate-spin" size={20} /></td></tr> : data.items.length === 0 ? <tr><td colSpan={7} className="py-12 text-center text-muted-foreground"><Banknote className="mx-auto mb-2 opacity-50" size={24} />Nenhum pagamento registrado nesta data.</td></tr> : data.items.map((payment) => <tr key={payment.id} className="border-b border-border last:border-0"><td className="whitespace-nowrap px-5 py-4 text-muted-foreground">{dateTime(payment.paidAt)}</td><td className="px-5 py-4 font-medium text-foreground">{payment.salonName}</td><td className="px-5 py-4 text-muted-foreground">{payment.planName || "-"}</td><td className="px-5 py-4 text-muted-foreground">{methodLabels[payment.paymentMethod]}</td><td className="px-5 py-4 text-muted-foreground">{payment.reference || "-"}</td><td className="px-5 py-4"><StatusBadge status={payment.status} /></td><td className="px-5 py-4 text-right font-semibold text-foreground">{currency(payment.amount)}</td></tr>)}</tbody></table></div>{data.totalPages > 1 && <div className="flex items-center justify-between border-t border-border px-5 py-3 text-sm"><span className="text-muted-foreground">{data.total} lançamento(s)</span><div className="flex gap-2"><button type="button" disabled={page === 1} onClick={() => setPage((value) => value - 1)} className="rounded border border-border px-3 py-1 disabled:opacity-50">Anterior</button><span className="self-center">{page} de {data.totalPages}</span><button type="button" disabled={page >= data.totalPages} onClick={() => setPage((value) => value + 1)} className="rounded border border-border px-3 py-1 disabled:opacity-50">Próximo</button></div></div>}</div>
    <Dialog open={modalOpen} onOpenChange={(open) => { if (!saving) setModalOpen(open); }}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>Registrar pagamento</DialogTitle><DialogDescription>Crie um lançamento para um recebimento manual de salão.</DialogDescription></DialogHeader><form onSubmit={(event) => void submitPayment(event)} className="space-y-4"><label className="block text-sm font-medium">Salão<select value={form.salonId} disabled={salonsLoading} onChange={(event) => setForm((value) => ({ ...value, salonId: event.target.value }))} className="mt-1 h-10 w-full rounded-lg border border-border bg-background px-3 text-sm"><option value="">{salonsLoading ? "Carregando..." : "Selecione o salão"}</option>{salons.map((salon) => <option key={salon.id} value={salon.id}>{salon.name}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">Valor (R$)<input inputMode="decimal" value={form.amount} onChange={(event) => setForm((value) => ({ ...value, amount: event.target.value }))} placeholder="0,00" className="mt-1 h-10 w-full rounded-lg border border-border bg-background px-3 text-sm" /></label><label className="text-sm font-medium">Data<input type="date" value={form.paidAt} onChange={(event) => setForm((value) => ({ ...value, paidAt: event.target.value }))} className="mt-1 h-10 w-full rounded-lg border border-border bg-background px-3 text-sm" /></label></div><label className="block text-sm font-medium">Forma de pagamento<select value={form.paymentMethod} onChange={(event) => setForm((value) => ({ ...value, paymentMethod: event.target.value as FinancialPaymentMethod }))} className="mt-1 h-10 w-full rounded-lg border border-border bg-background px-3 text-sm">{Object.entries(methodLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="block text-sm font-medium">Referência<input value={form.reference} onChange={(event) => setForm((value) => ({ ...value, reference: event.target.value }))} placeholder="Ex.: comprovante, ID da transação" className="mt-1 h-10 w-full rounded-lg border border-border bg-background px-3 text-sm" /></label><label className="block text-sm font-medium">Observação<textarea value={form.notes} onChange={(event) => setForm((value) => ({ ...value, notes: event.target.value }))} rows={3} className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm" /></label><DialogFooter><button type="button" disabled={saving} onClick={() => setModalOpen(false)} className="rounded-lg border border-border px-4 py-2 text-sm">Cancelar</button><button type="submit" disabled={saving} className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50">{saving && <Loader2 size={16} className="animate-spin" />}Registrar</button></DialogFooter></form></DialogContent></Dialog>
  </div>;
}

function SummaryCard({ icon: Icon, label, value, tone = "text-foreground" }: { icon: LucideIcon; label: string; value: string; tone?: string }) { return <div className="rounded-xl border border-border bg-card p-4"><div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">{label}</span><Icon size={18} className="text-muted-foreground" /></div><strong className={`mt-2 block text-2xl ${tone}`}>{value}</strong></div>; }
function StatusBadge({ status }: { status: FinancialPaymentStatus }) { const className: Record<FinancialPaymentStatus, string> = { paid: "bg-emerald-500/10 text-emerald-700", pending: "bg-amber-500/10 text-amber-700", refunded: "bg-destructive/10 text-destructive", cancelled: "bg-secondary text-muted-foreground" }; return <span className={`rounded-full px-2 py-1 text-xs font-medium ${className[status]}`}>{statusLabels[status]}</span>; }
